import { useEffect, useMemo, useState } from "react";
import type { ChangeEvent, FormEvent } from "react";
import { Download, Eye, FilePlus2, FileText, Loader2, Plus, Search, Trash2, Copy, Pencil } from "lucide-react";
import api from "../services/api";
import { getApiErrorMessage } from "../services/getApiErrorMessage";

type Template = { id: number; title: string; description?: string; subject?: string; grade_level?: string; learning_area?: string; file_name?: string; preview_path?: string; structure?: Record<string, string>; user?: { name: string }; created_at: string };
type Page = { data: Template[]; current_page: number; last_page: number; total: number };
const field = "mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm outline-none focus:border-sky-500 focus:ring-4 focus:ring-sky-100 dark:border-slate-700 dark:bg-slate-950 dark:focus:ring-sky-950";
const button = "inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800";

export function TemplateLibraryPage() {
  const [page, setPage] = useState<Page | null>(null); const [search, setSearch] = useState(""); const [subject, setSubject] = useState(""); const [grade, setGrade] = useState("");
  const [isOpen, setOpen] = useState(false); const [active, setActive] = useState<Template | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [form, setForm] = useState({ title: "", description: "", subject: "", grade_level: "", learning_area: "", file: null as File | null });
  const load = async (current = 1) => { setLoading(true); try { const r = await api.get<{ data: Page }>("/lesson-templates", { params: { page: current, search, subject, grade_level: grade } }); setPage(r.data.data); } catch (e) { setError(getApiErrorMessage(e, "Templates could not be loaded.")); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const subjects = useMemo(() => [...new Set((page?.data || []).map(t => t.subject).filter(Boolean))] as string[], [page]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); try { const data = new FormData(); Object.entries(form).forEach(([key, value]) => { if (value) data.append(key, value); }); await api.post("/lesson-templates", data); setNotice("Template uploaded and ready to use."); setOpen(false); setForm({ title: "", description: "", subject: "", grade_level: "", learning_area: "", file: null }); await load(); } catch (e) { setError(getApiErrorMessage(e, "Template upload failed.")); } finally { setSaving(false); } };
  const download = async (template: Template) => { try { const r = await api.get(`/lesson-templates/${template.id}/download`, { responseType: "blob" }); const href = URL.createObjectURL(r.data); const a = document.createElement("a"); a.href = href; a.download = template.file_name || `${template.title}.docx`; a.click(); URL.revokeObjectURL(href); } catch (e) { setError(getApiErrorMessage(e, "Document could not be downloaded.")); } };
  const preview = async (template: Template) => { setActive(template); };
  const remove = async (template: Template) => { if (!window.confirm(`Are you sure you want to delete "${template.title}"?`)) return; try { await api.delete(`/lesson-templates/${template.id}`); setNotice("Template deleted."); await load(page?.current_page); } catch (e) { setError(getApiErrorMessage(e, "Template could not be deleted.")); } };
  const duplicate = async (template: Template) => { try { await api.post(`/lesson-templates/${template.id}/duplicate`); setNotice("Template duplicated."); await load(page?.current_page); } catch (e) { setError(getApiErrorMessage(e, "Template could not be duplicated.")); } };
  const edit = async (template: Template) => { const title = window.prompt("Template name", template.title); if (title === null || !title.trim()) return; const description = window.prompt("Description", template.description || ""); if (description === null) return; try { await api.put(`/lesson-templates/${template.id}`, { title: title.trim(), description, subject: template.subject || "", grade_level: template.grade_level || "", learning_area: template.learning_area || "" }); setNotice("Template details updated."); await load(page?.current_page); } catch (e) { setError(getApiErrorMessage(e, "Template could not be updated.")); } };
  const useTemplate = (template: Template) => { localStorage.setItem("nexora_lesson_draft", JSON.stringify({ title: template.title, learningArea: template.learning_area || "", learningActivities: template.structure?.learningActivities || template.description || "", ...template.structure })); window.location.assign("/lessons"); };
  return <div className="mx-auto max-w-[1600px] space-y-5">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-sky-700 dark:text-sky-300">Template library</p><h1 className="mt-1 text-2xl font-semibold text-slate-950 dark:text-white">Lesson plan templates</h1><p className="mt-2 text-sm text-slate-500">Upload approved formats and start new lessons with a reusable structure.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white dark:bg-sky-600" onClick={() => setOpen(true)}><Plus className="size-4" /> Add New Template</button></div></section>
    {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{notice && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</p>}
    <section className="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900 md:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl border border-slate-300 px-3 dark:border-slate-700"><Search className="size-4 text-slate-400"/><input className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder="Search templates" value={search} onChange={e => setSearch(e.target.value)} /></label><select className="rounded-xl border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950" value={subject} onChange={e => setSubject(e.target.value)}><option value="">All subjects</option>{subjects.map(s => <option key={s}>{s}</option>)}</select><input className="rounded-xl border border-slate-300 px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950" placeholder="Grade level" value={grade} onChange={e => setGrade(e.target.value)} /><button className={button} onClick={() => void load()}>Apply filters</button></section>
    {loading ? <div className="py-16 text-center text-sm text-slate-500"><Loader2 className="mx-auto mb-2 animate-spin"/>Loading templates…</div> : <><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{page?.data.map(t => <article key={t.id} className="flex min-h-64 flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><FileText className="size-9 text-sky-600"/><p className="mt-4 text-xs font-semibold uppercase text-sky-700">{t.subject || "General"}{t.grade_level ? ` · ${t.grade_level}` : ""}</p><h2 className="mt-1 text-lg font-semibold text-slate-950 dark:text-white">{t.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-500">{t.description || "No description provided."}</p><p className="mt-3 text-xs text-slate-400">Uploaded {new Date(t.created_at).toLocaleDateString()} {t.user ? `by ${t.user.name}` : ""}</p><div className="mt-auto flex flex-wrap gap-2 pt-5"><button className={button} onClick={() => preview(t)}><Eye className="size-4"/>Preview</button><button className={button} onClick={() => useTemplate(t)}><FilePlus2 className="size-4"/>Use</button>{t.file_name && <button className={button} onClick={() => void download(t)}><Download className="size-4"/></button>}<button aria-label="Edit or rename" className={button} onClick={() => void edit(t)}><Pencil className="size-4"/></button><button aria-label="Duplicate" className={button} onClick={() => void duplicate(t)}><Copy className="size-4"/></button><button aria-label="Delete" className={button} onClick={() => void remove(t)}><Trash2 className="size-4"/></button></div></article>)}</div>{page?.data.length === 0 && <p className="py-14 text-center text-sm text-slate-500">No templates match these filters.</p>}<div className="flex items-center justify-between pt-3 text-sm text-slate-500"><span>{page?.total || 0} templates</span><div className="flex gap-2"><button className={button} disabled={!page || page.current_page === 1} onClick={() => void load((page?.current_page || 2) - 1)}>Previous</button><button className={button} disabled={!page || page.current_page === page.last_page} onClick={() => void load((page?.current_page || 0) + 1)}>Next</button></div></div></>}
    {isOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={submit} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-xl dark:bg-slate-900"><h2 className="text-lg font-semibold">Add New Template</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label>Template name<input required className={field} value={form.title} onChange={e => setForm({...form,title:e.target.value})}/></label><label>Subject<input className={field} value={form.subject} onChange={e => setForm({...form,subject:e.target.value})}/></label><label>Grade level<input className={field} value={form.grade_level} onChange={e => setForm({...form,grade_level:e.target.value})}/></label><label>Learning area<input className={field} value={form.learning_area} onChange={e => setForm({...form,learning_area:e.target.value})}/></label></div><label className="mt-3 block">Description<textarea className={field} value={form.description} onChange={e => setForm({...form,description:e.target.value})}/></label><label className="mt-3 block">Document <span className="text-xs text-slate-500">(DOC, DOCX, or PDF; 20MB max)</span><input accept=".doc,.docx,.pdf" className={field} type="file" onChange={(e: ChangeEvent<HTMLInputElement>) => setForm({...form,file:e.target.files?.[0] || null})}/></label><div className="mt-5 flex justify-end gap-2"><button className={button} type="button" onClick={() => setOpen(false)}>Cancel</button><button className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white dark:bg-sky-600" disabled={saving}>{saving ? "Uploading…" : "Upload and save"}</button></div></form></div>}
    {active && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><section className="max-h-[85vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white p-6 dark:bg-slate-900"><div className="flex justify-between gap-4"><div><h2 className="text-xl font-semibold">{active.title}</h2><p className="text-sm text-slate-500">{active.file_name || "Structured lesson template"}</p></div><button className={button} onClick={() => setActive(null)}>Close</button></div>{active.preview_path ? <Preview id={active.id}/> : <pre className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm dark:bg-slate-950">{active.description || "A document preview is unavailable for this file type. Download the original to view it."}</pre>}</section></div>}
  </div>;
}
function Preview({ id }: { id: number }) { const [text, setText] = useState("Loading preview…"); useEffect(() => { void api.get(`/lesson-templates/${id}/preview`, { responseType: "text" }).then(r => setText(r.data)).catch(() => setText("Preview unavailable. Download the original document to view it.")); }, [id]); return <pre className="mt-5 whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-6 dark:bg-slate-950">{text}</pre>; }
